### ISSUE TITLE
powers of two collide with each other

### ISSUE THREAD

**Issue by rmmh** [dzdx/pyintset#4]
* pyintset version: 0.1.4
* Python version: 2.7.15+ and 3.6.8
* Operating System: Ubuntu 18.04

### Description

Multiple powers of two appear to conflict when large:

```
>>> intset.IntSet([1<<32, 1<<33])                                                                                                                     
IntSet([4294967296])
>>> len(intset.IntSet([(1<<x) for x in range(50)]))                                                                                                   
34
```

**Comment by dzdx** [comment]
Thank you very much for using this library.
This problem is caused by insufficient length of the sign bit when comparing large numbers. This problem has been fixed and a new version has been released.

https://github.com/dzdx/pyintset/pull/5

**Comment by rmmh** [comment]
Thanks! :smile:
